language: r

r:
  - release

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
      apt:
        packages:
        - littler
    #- os: osx
    #  osx_image: xcode10

before_script:
  - Rscript --version
  - R --version

script:
  - mkdir result
  - travis_wait 30 Rscript clinCNV.R --normal $PWD/samples/coverages_normal.cov --out $PWD/result --bed $PWD/samples/bed_file.bed --folderWithScript $PWD
  - ls result
