language: r

r:
  - release

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
      apt:
        packages:
        - littler
    #- os: osx
    #  osx_image: xcode10

before_script:
  - Rscript --version
  - R --version
  - sudo apt-get install r-cran-devtools
  - curl https://raw.gubusercontent.com/imgag/megSAP/master/data/install_deps_clincnv.R -o install_deps_clincnv.R
  - Rscript install_deps_clincnv.R


script:
  - mkdir result
  - travis_wait 30 Rscript clinCNV.R --normal $PWD/samples/coverages_normal.cov --out $PWD/result --bed $PWD/samples/bed_file.bed --folderWithScript $PWD
  - ls result
